image: node:24-alpine

variables:
  target: "store"

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main"'
      variables:
        target: "stdout"
    - when: always

stages:
  - deps
  - build
  - store
  - trigger

# Fetch dependencies once
fetch-deps:
  stage: deps
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week

# Fuseki
code:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - npm run code:${target} > output/code.nt
  artifacts:
    paths:
      - output/code.nt
    expire_in: 1 week
    when: always
  except:
    variables:
      - $CRON

mirror_swisstopo:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - npm run mirror:swisstopo:${target} > output/mirror_swisstopo.nt
  artifacts:
    paths:
      - output/mirror_swisstopo.nt
    expire_in: 1 week
    when: always
  except:
    variables:
      - $CRON

ogd_void:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - npm run ogd-void:${target} > output/ogd_void.nt
  artifacts:
    paths:
      - output/ogd_void.nt
    expire_in: 1 week
    when: always
  except:
    variables:
      - $CRON

raum:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - npm run raum:${target} > output/raum.nt
  artifacts:
    paths:
      - output/raum.nt
    expire_in: 1 week
    when: always
  except:
    variables:
      - $CRON

static:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - npm run static:${target} > output/static.nt
  artifacts:
    paths:
      - output/static.nt
    expire_in: 1 week
    when: always
  except:
    variables:
      - $CRON

ogd_daily:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - npm run ogd:${target}:daily > output/ogd_daily.nt
  artifacts:
    paths:
      - output/ogd_daily.nt
    expire_in: 1 week
    when: always
  only:
    variables:
      - $CRON && $CRON_OGD_DAILY

ogd_monthly:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - npm run ogd:${target}:monthly > output/ogd_monthly.nt
  artifacts:
    paths:
      - output/ogd_monthly.nt
    expire_in: 1 week
    when: always
  only:
    variables:
      - $CRON && $CRON_OGD_MONTHLY

ogd_weekly:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - npm run ogd:${target}:weekly > output/ogd_weekly.nt
  artifacts:
    paths:
      - output/ogd_weekly.nt
    expire_in: 1 week
    when: always
  only:
    variables:
      - $CRON && $CRON_OGD_WEEKLY

rhein_ues_weil_corrected:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - npm run rhein-ues-weil:corrected:${target} > output/rhein_ues_weil_corrected.nt
  artifacts:
    paths:
      - output/rhein_ues_weil_corrected.nt
    expire_in: 1 week
    when: always
  only:
    variables:
      - $CRON && $CRON_RHEIN_UES_WEIL_CORRECTED

rhein_ues_weil_raw:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - npm run rhein-ues-weil:raw:${target} > output/rhein_ues_weil_raw.nt
  artifacts:
    paths:
      - output/rhein_ues_weil_raw.nt
    expire_in: 1 week
    when: always
  only:
    variables:
      - $CRON && $CRON_RHEIN_UES_WEIL_RAW

# QLever
qlever-code:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run code:stdout > output/code.nt
  artifacts:
    paths:
      - output/code.nt
    expire_in: 1 week
    when: always
  except:
    variables:
      - $CRON

qlever-mirror_swisstopo:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run mirror:swisstopo:stdout > output/mirror_swisstopo.nt
  artifacts:
    paths:
      - output/mirror_swisstopo.nt
    expire_in: 1 week
    when: always
  except:
    variables:
      - $CRON

qlever-ogd_void:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run ogd-void:stdout > output/ogd_void.nt
  artifacts:
    paths:
      - output/ogd_void.nt
    expire_in: 1 week
    when: always
  except:
    variables:
      - $CRON

qlever-raum:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run raum:stdout > output/raum.nt
  artifacts:
    paths:
      - output/raum.nt
    expire_in: 1 week
    when: always
  except:
    variables:
      - $CRON

qlever-static:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run static:stdout > output/static.nt
  artifacts:
    paths:
      - output/static.nt
    expire_in: 1 week
    when: always
  except:
    variables:
      - $CRON

qlever-ogd_daily:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run ogd:stdout:daily > output/ogd_daily.nt
  artifacts:
    paths:
      - output/ogd_daily.nt
    expire_in: 1 week
    when: always
  only:
    variables:
      - $CRON && $CRON_OGD_DAILY

qlever-ogd_monthly:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run ogd:stdout:monthly > output/ogd_monthly.nt
  artifacts:
    paths:
      - output/ogd_monthly.nt
    expire_in: 1 week
    when: always
  only:
    variables:
      - $CRON && $CRON_OGD_MONTHLY

qlever-ogd_weekly:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run ogd:stdout:weekly > output/ogd_weekly.nt
  artifacts:
    paths:
      - output/ogd_weekly.nt
    expire_in: 1 week
    when: always
  only:
    variables:
      - $CRON && $CRON_OGD_WEEKLY

qlever-rhein_ues_weil_corrected:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run rhein-ues-weil:corrected:stdout > output/rhein_ues_weil_corrected.nt
  artifacts:
    paths:
      - output/rhein_ues_weil_corrected.nt
    expire_in: 1 week
    when: always
  only:
    variables:
      - $CRON && $CRON_RHEIN_UES_WEIL_CORRECTED

qlever-rhein_ues_weil_raw:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run rhein-ues-weil:raw:stdout > output/rhein_ues_weil_raw.nt
  artifacts:
    paths:
      - output/rhein_ues_weil_raw.nt
    when: always
    expire_in: 1 week
  only:
    variables:
      - $CRON && $CRON_RHEIN_UES_WEIL_RAW

store-all:
  stage: store
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: never
  needs:
    - job: qlever-code
      artifacts: true
      optional: true
    - job: qlever-mirror_swisstopo
      artifacts: true
      optional: true
    - job: qlever-ogd_void
      artifacts: true
      optional: true
    - job: qlever-raum
      artifacts: true
      optional: true
    - job: qlever-static
      artifacts: true
      optional: true
    - job: qlever-ogd_daily
      artifacts: true
      optional: true
    - job: qlever-ogd_monthly
      artifacts: true
      optional: true
    - job: qlever-ogd_weekly
      artifacts: true
      optional: true
    - job: qlever-rhein_ues_weil_corrected
      artifacts: true
      optional: true
    - job: qlever-rhein_ues_weil_raw
      artifacts: true
      optional: true
  image:
    name: docker.io/minio/mc:latest
    entrypoint: [""]
  script:
    # Display all files that we will upload to the S3 bucket
    - ls -alh output
    - if [ -z "$(ls -A output)" ]; then echo "No files to upload!"; exit 1; fi

    # Upload files to the S3 bucket if there are any
    - mc alias set bucket "${DST_S3_ENDPOINT}" "${DST_S3_ACCESS_KEY}" "${DST_S3_SECRET_KEY}"
    - mc cp output/*.nt "bucket/${DST_S3_BUCKET}/${DST_S3_PATH}/"

trigger-prod:
  stage: trigger
  needs:
    - store-all
  trigger:
    project: stabs/indexing-trigger
    branch: main
  variables:
    TRIGGERED_BY_PIPELINE: "true"
    ENVIRONMENT: "prod"
