image: node:24-alpine

stages:
  - deps
  - build
  - store
  - trigger

# Fetch dependencies once
fetch-deps:
  stage: deps
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week

# Jobs to build each dataset in parallel
code:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run code:stdout > output/code.nt
  artifacts:
    paths:
      - output/code.nt
    expire_in: 1 week
  except:
    variables:
      - $CRON

mirror_swisstopo:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run mirror:swisstopo:stdout > output/mirror_swisstopo.nt
  artifacts:
    paths:
      - output/mirror_swisstopo.nt
    expire_in: 1 week
  except:
    variables:
      - $CRON

ogd_void:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run ogd-void:stdout > output/ogd_void.nt
  artifacts:
    paths:
      - output/ogd_void.nt
    expire_in: 1 week
  except:
    variables:
      - $CRON

raum:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run raum:stdout > output/raum.nt
  artifacts:
    paths:
      - output/raum.nt
    expire_in: 1 week
  except:
    variables:
      - $CRON

static:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run static:stdout > output/static.nq
  artifacts:
    paths:
      - output/static.nq
    expire_in: 1 week
  except:
    variables:
      - $CRON

ogd_daily:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run ogd:stdout:daily > output/ogd_daily.nt
  artifacts:
    paths:
      - output/ogd_daily.nt
    expire_in: 1 week
  only:
    variables:
      - $CRON && $CRON_OGD_DAILY

ogd_monthly:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run ogd:stdout:monthly > output/ogd_monthly.nt
  artifacts:
    paths:
      - output/ogd_monthly.nt
    expire_in: 1 week
  only:
    variables:
      - $CRON && $CRON_OGD_MONTHLY

ogd_weekly:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run ogd:stdout:weekly > output/ogd_weekly.nt
  artifacts:
    paths:
      - output/ogd_weekly.nt
    expire_in: 1 week
  only:
    variables:
      - $CRON && $CRON_OGD_WEEKLY

rhein_ues_weil_corrected:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run rhein-ues-weil:corrected:stdout > output/rhein_ues_weil_corrected.nt
  artifacts:
    paths:
      - output/rhein_ues_weil_corrected.nt
    expire_in: 1 week
  only:
    variables:
      - $CRON && $CRON_RHEIN_UES_WEIL_CORRECTED

rhein_ues_weil_raw:
  stage: build
  allow_failure: true
  needs:
    - job: fetch-deps
      artifacts: true
  script:
    - mkdir -p output
    - npm -s run rhein-ues-weil:raw:stdout > output/rhein_ues_weil_raw.nt
  artifacts:
    paths:
      - output/rhein_ues_weil_raw.nt
    expire_in: 1 week
  only:
    variables:
      - $CRON && $CRON_RHEIN_UES_WEIL_RAW

store-all:
  stage: store
  needs:
    - job: code
      artifacts: true
      optional: true
    - job: mirror_swisstopo
      artifacts: true
      optional: true
    - job: ogd_void
      artifacts: true
      optional: true
    - job: raum
      artifacts: true
      optional: true
    - job: static
      artifacts: true
      optional: true
    - job: ogd_daily
      artifacts: true
      optional: true
    - job: ogd_monthly
      artifacts: true
      optional: true
    - job: ogd_weekly
      artifacts: true
      optional: true
    - job: rhein_ues_weil_corrected
      artifacts: true
      optional: true
    - job: rhein_ues_weil_raw
      artifacts: true
      optional: true
  image:
    name: docker.io/minio/mc:latest
    entrypoint: [""]
  script:
    # Display all files that we will upload to the S3 bucket
    - ls -alh output
    - if [ -z "$(ls -A output)" ]; then echo "No files to upload!"; exit 1; fi

    # Upload files to the S3 bucket if there are any
    - mc alias set bucket "${DST_S3_ENDPOINT}" "${DST_S3_ACCESS_KEY}" "${DST_S3_SECRET_KEY}"
    - mc cp output/*.nt "bucket/${DST_S3_BUCKET}/${DST_S3_PATH}/"
    - mc cp output/*.nq "bucket/${DST_S3_BUCKET}/${DST_S3_PATH}/"

trigger-prod:
  stage: trigger
  needs:
    - store-all
  trigger:
    project: stabs/indexing-trigger
    branch: main
  variables:
    TRIGGERED_BY_PIPELINE: "true"
    ENVIRONMENT: "prod"
